/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50525
Source Host           : localhost:3306
Source Database       : yii2reportbk

Target Server Type    : MYSQL
Target Server Version : 50525
File Encoding         : 65001

Date: 2017-05-15 23:02:20
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for pttype
-- ----------------------------
DROP TABLE IF EXISTS `pttype`;
CREATE TABLE `pttype` (
  `pttype` char(2) NOT NULL,
  `name` varchar(250) DEFAULT NULL,
  `editmask` varchar(100) DEFAULT NULL,
  `isuse` char(1) DEFAULT NULL,
  `pcode` char(2) DEFAULT NULL,
  `requirecode` char(1) DEFAULT NULL,
  `doctor_fee` char(1) DEFAULT NULL,
  `fee_code` varchar(7) DEFAULT NULL,
  `discount` int(11) DEFAULT NULL,
  `contract` char(1) DEFAULT NULL,
  `paidst` char(2) DEFAULT NULL,
  `in_region` char(1) DEFAULT NULL,
  `uc` char(1) DEFAULT NULL,
  `require_hcode` char(1) DEFAULT NULL,
  `oldcode` varchar(5) DEFAULT NULL,
  `fee_code2` varchar(7) DEFAULT NULL,
  `price_type` int(11) DEFAULT NULL,
  `debtor` char(1) DEFAULT NULL,
  `noexpire` char(1) DEFAULT NULL,
  `hipdata_code` varchar(6) DEFAULT NULL,
  `min_age` int(11) DEFAULT NULL,
  `max_age` int(11) DEFAULT NULL,
  `bill_sss` char(1) DEFAULT NULL,
  `bill_type` int(11) DEFAULT NULL,
  `hipdata_pttype` char(3) DEFAULT NULL,
  `use_contract_id` char(1) DEFAULT NULL,
  `yearly_charge` char(1) DEFAULT NULL,
  `yearly_charge_icode1` varchar(7) DEFAULT NULL,
  `yearly_charge_icode2` varchar(7) DEFAULT NULL,
  `region_type` int(11) DEFAULT NULL,
  `pttype_group1` char(3) DEFAULT NULL,
  `pttype_group2` char(3) DEFAULT NULL,
  `pttype_guid` varchar(38) DEFAULT NULL,
  `max_debt_money` double(15,3) DEFAULT NULL,
  `allow_finance_edit` char(1) DEFAULT NULL,
  `print_csmb_statement` char(1) DEFAULT NULL,
  `pttype_information` longtext,
  `fee_code_paidst` char(2) DEFAULT NULL,
  `fee_code2_paidst` char(2) DEFAULT NULL,
  `debt_due_day` int(11) DEFAULT NULL,
  `rx_pay_debit_tr` char(1) DEFAULT NULL,
  `separate_rcpno` char(1) DEFAULT NULL,
  `rcp_bookno` int(11) DEFAULT NULL,
  `separate_debt_id` char(1) DEFAULT NULL,
  `admit_fee_code` varchar(7) DEFAULT NULL,
  `use_package` char(1) DEFAULT NULL,
  `charge_df_perday` char(1) DEFAULT NULL,
  `nhso_code` char(2) DEFAULT NULL,
  `ipd_hour_cut` int(11) DEFAULT NULL,
  `pttype_spp_id` int(11) DEFAULT NULL,
  `print_presc_ned` char(1) DEFAULT NULL,
  `hos_guid` varchar(38) DEFAULT NULL,
  `sks_benefit_plan_type_id` int(11) DEFAULT NULL,
  `pttype_std_code` char(4) DEFAULT NULL,
  `export_eclaim` char(1) DEFAULT NULL,
  `round_money` char(1) DEFAULT NULL,
  `pttype_price_policy_type_id` int(11) DEFAULT NULL,
  `emp_privilege` char(1) DEFAULT NULL,
  `is_pttype_plan` char(1) DEFAULT NULL,
  `finance_round_money` char(1) DEFAULT NULL,
  `emp_financial` char(1) DEFAULT NULL,
  `pttype_eclaim_id` varchar(2) DEFAULT NULL,
  `pttype_price_group_id` int(11) DEFAULT NULL,
  `calc_discount` char(1) DEFAULT NULL,
  `debt_finance_limit` double(15,3) DEFAULT NULL,
  `debt_finance_pttype` char(2) DEFAULT NULL,
  `opbkk_type_code` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`pttype`),
  KEY `name` (`name`),
  KEY `ix_ix_hipdata_code` (`hipdata_code`),
  KEY `ix_pcode` (`pcode`),
  KEY `ix_pttype_spp_id` (`pttype_spp_id`),
  KEY `ix_pttype_guid` (`pttype_guid`),
  KEY `ix_nhso_code` (`nhso_code`)
) ENGINE=MyISAM DEFAULT CHARSET=tis620;

-- ----------------------------
-- Records of pttype
-- ----------------------------
INSERT INTO `pttype` VALUES ('06', '06:ผู้พิการ (นอกเขต)', '', 'Y', 'AD', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'Y', 'UCS', null, null, 'N', null, '74', 'N', 'N', null, null, '1', null, null, '{EB47F76F-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '74', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '03', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('07', '07:นักเรียน ม.ต้น (นอกเขต)', '', 'Y', 'AC', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '73', 'N', 'N', null, null, '1', null, null, '{EB47FA3C-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '01', null, null, null, null, null, null, null, null, 'Y', '73', '6', '4', null, null, '3', null, 'Y', 'Y', null, null, null, null, null, '08', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('08', '08:ภิกษุ สามเณร(นอกเขต)', '', 'Y', 'AF', 'Y', 'Y', '3000047', null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'N', 'UCS', null, null, 'N', '0', '76', 'N', 'N', null, null, '1', null, null, '{EB47FB19-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '76', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '08', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('10', '10:ชำระเงิน(จ่ายสด)', '', 'Y', 'A1', 'N', 'Y', null, '0', 'N', '03', null, null, 'N', null, null, '0', 'N', null, 'UCS', null, null, 'N', '0', '10', 'N', 'N', null, null, '5', null, null, '{EB47FBC2-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '06', '6', '6', null, null, '1', null, 'Y', 'Y', null, null, null, null, null, '27', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('12', '12: ตรวจสุภาพแรงงานต่างด้าว', '', 'Y', 'A1', 'Y', 'N', null, null, 'N', '03', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '07', 'N', 'N', null, null, '1', null, null, '{EB47FC6B-3923-11E7-BC2E-0894EF2FC582}', null, 'N', null, null, null, null, null, null, null, null, null, null, null, 'Y', '07', '6', '5', null, null, '3', null, 'Y', 'Y', null, null, null, null, null, '21', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('20', '20 : เบิกได้(จ่ายเงินสด)', '', 'Y', 'A2', 'Y', 'Y', null, '0', 'N', '01', null, null, 'N', null, null, '0', 'Y', 'Y', 'OFC', null, null, 'N', '0', '02', 'N', 'N', null, null, '1', null, null, '{EB47FD11-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', 'Y', null, null, null, null, null, '16', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('21', '21:ลูกหนี้ค่าตรวจสุขภาพหน่วยงานภาครัฐ', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'N', null, null, '0', 'Y', 'Y', 'OFC', null, null, 'N', '0', '02', 'N', 'N', null, null, '1', null, null, '{EB47FDB0-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, null, '02', '6', '1', 'Y', null, '2', null, 'Y', 'Y', null, null, null, null, null, '16', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('40', '40:ผู้มีสิทธิลดหย่อนตามระเบียบ สธ', '', 'N', 'AI', 'Y', 'N', null, '0', 'N', '02', null, null, 'N', null, null, '0', 'Y', null, 'UCS', null, null, 'N', null, '40', 'N', 'N', null, null, '1', null, null, '{EB47FE4F-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '78', '6', '4', null, null, null, null, null, null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('45', '45:ผู้ป่วยในโครงการพระบรมราชานุเคราะห์', '', 'Y', 'AI', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '45', 'N', 'N', null, null, '1', null, null, '{EB47FEF0-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '78', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('50', '50:ผู้ป่วยใช้ พ.ร.บ.', '', 'Y', 'A9', 'N', 'Y', null, null, 'N', '02', null, null, 'N', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '50', 'N', 'N', null, null, '2', null, null, '{EB47FFB8-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'N', '06', '6', '6', null, null, '7', null, 'Y', 'Y', null, null, null, null, null, '28', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('60', '60:อาสาสมัครมาเลเรีย', '', 'Y', 'AJ', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '60', 'N', 'N', null, null, '1', null, null, '{EB48005C-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '60', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('61', '61:ครอบครัวอาสาสมัครมาเลเรีย', '', 'Y', 'AJ', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '61', 'N', 'N', null, null, '1', null, null, '{EB4800F1-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '61', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('62', '62:ช่างสุขภัณฑ์หมู่บ้าน', '', 'Y', 'AI', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '62', 'N', 'N', null, null, '1', null, null, '{EB480188-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '78', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('63', '63:ครอบครัวของช่างสุขภัณฑ์หมู่บ้าน', '', 'Y', 'AI', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '78', 'N', 'N', null, null, '1', null, null, '{EB480224-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '78', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('64', '64:ผู้บริหารและครูของโรงเรียนเอกชนที่สอนศาสนาอิสลาม', '', 'N', 'A7', 'Y', 'Y', null, '0', 'N', '02', null, null, 'N', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', null, 'N', 'N', null, null, '1', null, null, '{EB4802C1-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '16', '6', '2', null, null, '4', null, null, null, null, null, null, null, null, '16', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('65', '65:ครอบครัวผู้บริหารร.ร.และครูสอนศาสนาอิสลาม', '', 'N', 'A7', 'Y', 'N', null, '0', 'N', '02', null, null, 'N', null, null, '0', 'Y', null, 'UCS', null, null, 'N', null, null, 'N', 'N', null, null, '1', null, null, '{EB480364-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, null, '16', '6', '2', null, null, '4', null, null, null, null, null, null, null, null, '16', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('66', '66:ผู้ได้รับพระราชทานเหรียญชายแดน', '', 'Y', 'AE', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '66', 'N', 'N', null, null, '2', null, null, '{EB480401-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '66', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('67', '67:ผู้ได้รับพระราชทานเหรียญเสรีชน', '', 'Y', 'AE', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '67', 'N', 'N', null, null, '2', null, null, '{EB48049B-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '67', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('68', '68:ผู้บริจาคโลหิตครบ 18ครั้ง', '', 'Y', 'AI', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '68', 'N', 'N', null, null, '3', null, null, '{EB4805C3-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '68', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('71', '71:เด็ก 0-12ปี (ในเขต)', '', 'Y', 'AA', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '71', 'N', 'N', null, null, '1', null, null, '{EB480673-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '71', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('72', '72:ผู้ป่วยรายได้น้อย(ในเขต)', '', 'Y', 'AB', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '72', 'N', 'N', null, null, '1', null, null, '{EB48070B-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '72', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('73', '73:นักเรียน ม.ต้น (ในเขต)', '', 'Y', 'AC', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '73', 'N', 'N', null, null, '1', null, null, '{EB48079F-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '73', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('74', '74:ผู้พิการ (ในเขต)', '', 'Y', 'AD', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'Y', 'UCS', null, null, 'N', '0', '74', 'N', 'N', null, null, '1', null, null, '{EB480833-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '74', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('75', '75:ทหารผ่านศึก', '', 'Y', 'AE', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '75', 'N', 'N', null, null, '1', null, null, '{EB4808C6-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '98', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('76', '76:ภิกษุ สามเณร(ในเขต)', '', 'Y', 'AF', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'N', 'UCS', null, null, 'N', '0', '76', 'N', 'N', null, null, '1', null, null, '{EB480959-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '76', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('77', '77:ผู้สูงอายุ(ในเขต) 60 ปีขึ้นไป', '', 'Y', 'AG', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'Y', 'UCS', null, null, 'N', null, '77', 'N', 'N', null, null, '1', null, null, '{EB4809F3-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '77', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('78', '78:ผู้สูงอายุ(นอกเขต) 60 ปีขึ้นไป', '', 'Y', 'AG', 'Y', 'Y', null, '0', 'N', '02', 'Y', null, 'Y', null, '', '0', 'Y', 'Y', 'UCS', null, null, 'N', '0', '78', 'N', 'N', null, null, '1', null, null, '{EB480A8B-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '01', null, null, null, null, null, null, null, null, 'Y', '77', '6', '4', null, null, '3', null, 'Y', 'Y', null, null, null, null, null, '08', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('79', '79:เด็ก 0-12ปี (นอกเขต)', '', 'Y', 'AA', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '71', 'N', 'N', null, null, '1', null, null, '{EB480B26-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '71', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '08', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('80', '80:ครอบครัวทหารผ่านศึก', '', 'Y', 'AE', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'N', 'UCS', null, null, 'N', '0', '80', 'N', 'N', null, null, '1', null, null, '{EB480BB9-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '98', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('81', '81:ผู้นำชุมชน', '', 'Y', 'AK', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'N', 'UCS', null, null, 'N', '0', '81', 'N', 'N', null, null, '1', null, null, '{EB480C4E-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '81', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('82', '82: อสม.(ในเขต)', '', 'Y', 'AJ', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'N', 'UCS', null, null, 'N', '0', '82', 'N', 'N', null, null, '1', null, null, '{EB480CE2-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '82', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('83', '83:ผู้นำศาสนาอิสลามที่มีการรับรอง', '', 'N', 'AF', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', null, null, 'N', 'N', null, null, '1', null, null, '{EB480D79-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '83', '6', '4', null, null, '3', null, null, null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('84', '84:ครอบครัวผู้นำศาสนาอิสลาม', '', 'N', 'AF', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', null, null, 'N', 'N', null, null, '1', null, null, '{EB480E12-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '83', '6', '4', null, null, '3', null, null, null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('85', '85:ผู้ได้รับพระราชทานเหรียญงานสงครามยุโรป', '', 'N', 'AE', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '85', 'N', 'N', null, null, '2', null, null, '{EB480EA5-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '98', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('86', '86:ครอบครัวเหรียญสงครามยุโรป', '', 'N', 'AE', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', null, '86', 'N', 'N', null, null, '2', null, null, '{EB480F4A-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '98', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('87', '87:บุคคลในครอบครัวผู้นำชุมชน', '', 'Y', 'AK', 'Y', 'Y', '', '0', 'N', '02', 'Y', null, 'Y', null, '', '0', 'Y', 'N', 'UCS', null, null, 'N', '0', '87', 'N', 'N', null, null, '1', null, null, '{EB480FF2-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '87', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('88', '88:บุคคลในครอบครัวอสม.', '', 'Y', 'AJ', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'N', 'UCS', null, null, 'N', '0', '88', 'N', 'N', null, null, '1', null, null, '{EB481086-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '02', null, null, null, null, null, null, null, null, 'Y', '82', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('89', '89:บัตรทอง(ในเขต) 12-59 ปี', '', 'Y', 'UC', 'Y', 'Y', '3000225', '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'N', 'UCS', null, null, 'N', '0', '89', 'N', 'N', null, null, '1', null, null, '{EB48115F-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, '03', null, null, null, null, null, null, null, null, 'N', '89', '6', '3', null, null, '3', null, 'Y', null, null, null, null, null, null, '02', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('90', '90:ทหารเกณฑ์', '', 'Y', 'AE', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', null, '90', 'N', 'N', null, null, '1', null, null, '{EB481203-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '90', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '09', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('91', '91:ผู้ที่อยู่ภายใต้การดูแลของกรมราชทัณฑ์', '', 'Y', 'AI', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', null, '91', 'N', 'N', null, null, '1', null, null, '{EB48129B-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '91', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('92', '92:ผู้ที่อยู่ในสถานพินิจ/สงเคราะห์', '', 'Y', 'AI', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', null, '91', 'N', 'N', null, null, '1', null, null, '{EB481338-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '91', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('93', '93:นักเรียนทหาร', '', 'Y', 'AC', 'Y', 'Y', null, '0', 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '93', 'N', 'N', null, null, '1', null, null, '{EB4813D4-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '93', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '01', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('94', '94:ต่างด้าวขึ้นทะเบียน 30 บาท', '', 'Y', 'AL', 'Y', 'Y', '3004569', '0', 'N', '02', 'Y', null, 'Y', null, '', '0', 'Y', 'N', 'UCS', '0', '0', 'N', '0', '94', 'N', 'N', null, null, '1', null, null, '{EB481466-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, 'Y', null, null, null, null, null, 'Y', '07', '6', '5', null, null, '3', null, 'Y', 'Y', null, null, null, null, null, '21', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('95', '95:บัตรทอง(นอกเขต) 12-59 ปี', '', 'Y', 'UC', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '89', 'N', 'N', null, null, '1', null, null, '{EB4814FE-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '89', '6', '3', null, null, '3', null, 'Y', null, null, null, null, null, null, '08', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('96', '96:ผู้ป่วยรายได้น้อย(นอกเขต)', '', 'Y', 'AB', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '72', 'N', 'N', null, null, '1', null, null, '{EB4815D1-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '72', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '08', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('97', '97:อสม.(นอกเขต)', '', 'Y', 'AJ', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '82', 'N', 'N', null, null, '1', null, null, '{EB48166B-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '82', '6', '4', null, null, '3', null, 'Y', 'Y', null, null, null, null, null, '08', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('98', '98:เด็กแรกเกิด', '', 'Y', 'AA', 'N', 'Y', null, null, 'N', '02', null, null, 'N', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '71', 'N', 'N', null, null, '1', null, null, '{EB481703-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '71', '6', '4', null, null, '3', null, 'Y', null, null, null, null, null, null, '03', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('99', '99:สิทธิว่าง', '', 'Y', 'UC', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', '89', 'N', 'N', null, null, '1', null, null, '{EB481795-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '89', '6', '3', null, null, '3', null, 'Y', null, null, null, null, null, null, '03', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('B1', 'B1:จ่ายตรง กทม.(ข้าราชการ)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'LGO', null, null, 'N', '0', 'B1', 'N', 'N', null, null, '4', null, null, '{EB481828-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '19', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('B2', 'B2:จ่ายตรง กทม.(ลูกจ้างประจำ)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'LGO', null, null, 'N', '0', 'B2', 'N', 'N', null, null, '4', null, null, '{EB4818C6-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '19', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('B3', 'B3:จ่ายตรง กทม.(ผู้รับเบี้ยหวัดบำนาญ)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'LGO', null, null, 'N', '0', 'B3', 'N', 'N', null, null, '4', null, null, '{EB481959-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '19', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('B4', 'B4:จ่ายตรง กทม.(บุคคลในครอบครัว)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'LGO', null, null, 'N', '0', 'B4', 'N', 'N', null, null, '4', null, null, '{EB4819EF-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '19', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('B5', 'B5:จ่ายตรง กทม.(บุคคลในครอบครัวผู้รับเบี้ยหวัดบำนาญ)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'LGO', null, null, 'N', '0', 'B5', 'N', 'N', null, null, '4', null, null, '{EB481A84-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '19', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('L1', 'L1:จ่ายตรง-อปท.(ข้าราชการ/พนักงาน/ลูกจ้างประจำ/ครูผู้ดูแลเด็ก/ครูผู้ช่วย)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'LGO', null, null, 'N', '0', 'L1', 'N', 'N', null, null, '4', null, null, '{EB481B20-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '18', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('L2', 'L2:จ่ายตรง-อปท.(บุคคลในครอบครัว)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'LGO', null, null, 'N', '0', 'L2', 'N', 'N', null, null, '4', null, null, '{EB481BC2-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '18', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('L3', 'L3:จ่ายตรง-อปท.(ผู้รับเบี้ยหวัดบำนาญ)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'LGO', null, null, 'N', '0', 'L3', 'N', 'N', null, null, '4', null, null, '{EB481C59-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '18', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('L4', 'L4:จ่ายตรง-อปท.(บุคคลในครอบครัวผู้รับเบี้ยหวัดบำนาญ)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'N', 'LGO', null, null, 'N', '0', 'L4', 'N', 'N', null, null, '4', null, null, '{EB481CEB-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '18', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('L5', 'L5:จ่ายตรง-อปท.(ข้าราชการการเมือง)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'LGO', null, null, 'N', '0', 'L5', 'N', 'N', null, null, '4', null, null, '{EB481D82-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '18', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('L6', 'L6:จ่ายตรง-อปท.(บุคคลในครอบครัวข้าราชการการเมือง)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'N', 'LGO', null, null, 'N', '0', 'L6', 'N', 'N', null, null, '4', null, null, '{EB481E16-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '18', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('O1', 'O1:จ่ายตรง-สกส.(ข้าราชการ)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', 'N', 'OFC', null, null, 'N', '0', 'O1', 'N', 'N', null, null, '4', null, null, '{EB481EAE-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', 'O1', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '17', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('O2', 'O2:จ่ายตรง-สกส.(ลูกจ้างประจำ)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'OFC', null, null, 'N', '0', 'O2', 'N', 'N', null, null, '4', null, null, '{EB481F4B-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '17', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('O3', 'O3:จ่ายตรง-สกส.(ผู้รับเบี้ยหวัดบำนาญ)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'OFC', null, null, 'N', '0', 'O2', 'N', 'N', null, null, '4', null, null, '{EB481FDE-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '17', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('O4', 'O4:จ่ายตรง-สกส.(บุคคลในครอบครัว)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'OFC', null, null, 'N', '0', 'O4', 'N', 'N', null, null, '4', null, null, '{EB482071-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '17', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('O5', 'O5:จ่ายตรง-สกส.(บุคคลในครอบครัวผู้รับเบี้ยหวัดบำนาญ)', '', 'Y', 'A2', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'OFC', null, null, 'N', '0', 'O5', 'N', 'N', null, null, '4', null, null, '{EB482106-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '02', '6', '1', 'Y', null, '2', null, 'Y', null, null, null, null, null, null, '17', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('S1', 'S1:ปกส. ในเขต(ผู้ประกันตน)', '', 'Y', 'A7', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'SSS', null, null, 'N', '0', 'S1', 'N', 'N', null, null, '4', null, null, '{EB4821B6-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', 'S1', '6', '2', 'Y', null, '4', null, 'Y', 'Y', null, null, null, null, null, '10', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('S4', 'S4:ประกันสังคมทุพลภาพ', '', 'Y', 'A7', 'Y', 'Y', null, null, 'N', '02', null, null, 'N', null, null, '0', 'Y', null, 'SSS', null, null, 'N', null, 'S4', 'N', 'N', null, null, '4', null, null, '{EB482249-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '01', '6', '2', null, null, '4', null, 'Y', 'Y', null, null, null, null, null, '15', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('S5', 'S5:ประกันสังคมกองทุนทดแทน', '', 'Y', 'A7', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'SSS', null, null, 'N', null, 'S5', 'N', 'N', null, null, '1', null, null, '{EB4822DC-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '01', '6', '2', null, null, '4', null, 'Y', 'Y', null, null, null, null, null, '13', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('S6', 'S6:ประกันสังคม 72 ชั่วโมง', '', 'Y', 'A7', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'SSS', null, null, 'N', null, 'S6', 'N', 'N', null, null, '1', null, null, '{EB48236F-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '01', '6', '2', null, null, '4', null, 'Y', 'Y', null, null, null, null, null, '14', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('SS', 'SS:ประกันสังคม(นอกเขต)', '', 'Y', 'A7', 'Y', 'Y', null, '0', 'N', '02', 'Y', null, 'Y', null, '', '0', 'Y', 'N', 'SSS', '0', '0', 'N', '0', 'SS', 'N', 'N', null, null, '1', null, null, '{EB482401-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '01', '6', '2', 'Y', null, '4', null, 'Y', 'Y', null, null, null, null, null, '11', null, null, null, null, null);
INSERT INTO `pttype` VALUES ('ST', 'ST:บุคคลที่มีปัญหาสถานะสิทธิ', '', 'Y', 'UC', 'Y', 'Y', null, null, 'N', '02', null, null, 'Y', null, null, '0', 'Y', null, 'UCS', null, null, 'N', '0', 'ST', 'N', 'N', null, null, '4', null, null, '{EB482497-3923-11E7-BC2E-0894EF2FC582}', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Y', '06', '6', '2', 'N', null, '4', null, 'Y', 'Y', null, null, null, null, null, '25', null, null, null, null, null);
